spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: manager
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto:  update   
  mvc:
    view: 
      prefix: /views/
      suffix: .jsp

server:
  port: 8090
  servlet:
    context-path: /MyBook
  
  